#############################################################################
# Generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#  Nov 06, 2018 02:20:02 PM CET  platform: Linux
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

vTcl:font:add_GUI_font TkDefaultFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkFixedFont \
"-family monospace -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkMenuFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
vTcl:font:add_GUI_font TkTextFont \
"-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"
set vTcl(actual_gui_font_dft_name) TkDefaultFont
set vTcl(actual_gui_font_menu_name) TkMenuFont
set vTcl(actual_gui_bg) wheat
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) wheat
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #b2c9f4
set vTcl(analog_color_p) #eaf4b2
set vTcl(analog_color_m) #f4bcb2
set vTcl(active_fg) #111111
set vTcl(actual_gui_menu_active_bg)  #f4bcb2
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family RaghuMalayalam -size 12 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top32
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top32
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top32 {base} {
    if {$base == ""} {
        set base .top32
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m33" -background {#f4ecd2} -highlightbackground wheat \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 1000x500+386+107
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1905 1170
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Isaac"
    vTcl:DefineAlias "$top" "IsaacInterface" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m33
    menu $site_3_0 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#9b9b9b} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0 add cascade \
        -menu "$site_3_0.men34" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#990000} -compound left \
        -font [vTcl:font:getFontFromDescr "-family RaghuMalayalam -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground {#ffff00} -label File 
    menu $site_3_0.men34 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ff0000} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men34 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#ff0000} -command {#save} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground white -label Save 
    $site_3_0.men34 add separator \
        -background {#ff0000} 
    $site_3_0.men34 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#ff0000} -command {#quit} -compound top \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground white -label Quit 
    $site_3_0 add cascade \
        -menu "$site_3_0.men34" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#990000} -compound left \
        -font [vTcl:font:getFontFromDescr "-family RaghuMalayalam -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground {#ffff00} -label File -menu "$site_3_0.men32" \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#990000} -compound left \
        -font [vTcl:font:getFontFromDescr "-family RaghuMalayalam -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground {#ffff00} -label Edit 
    menu $site_3_0.men32 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ff0000} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men32 add command \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#ff0000} -command {#cut} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground white -label Cut 
    $site_3_0.men32 add command \
        -activebackground {#d9d9d9} -activeforeground black \
        -background {#ff0000} -command {#copy} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground white -label Copy 
    $site_3_0.men32 add separator \
        -background {#ff0000} 
    $site_3_0.men32 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#ff0000} -command {#paste} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground white -label Paste 
    $site_3_0.men32 add cascade \
        -menu "$site_3_0.men32.men32" -activebackground white \
        -activeforeground {#000000} -background {#ff0000} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground white -label Other 
    set site_4_0 $site_3_0.men32
    menu $site_4_0.men32 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ff0000} -font TkMenuFont -foreground black -tearoff 0 
    $site_4_0.men32 add command \
        -background {#ffff00} -command {#post} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label Post 
    $site_4_0.men32 add command \
        -background {#ffff00} -command {#sync} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label Sync 
    $site_4_0.men32 add cascade \
        -menu "$site_4_0.men32.men32" -background {#ffff00} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label Still 
    set site_5_0 $site_4_0.men32
    menu $site_5_0.men32 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ff0000} -font TkMenuFont -foreground black -tearoff 0 
    $site_5_0.men32 add command \
        -background plum -command {#yes} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label Yes 
    $site_5_0.men32 add command \
        -background plum -command {#no} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label No 
    $site_5_0.men32 add checkbutton \
        -variable IRS -background plum \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label IRS 
    $site_5_0.men32 add checkbutton \
        -variable Charity -background plum \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label Charity 
    $site_5_0.men32 add cascade \
        -menu "$site_5_0.men32.men32" -background plum \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -label More 
    set site_6_0 $site_5_0.men32
    menu $site_6_0.men32 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#ff0000} -font TkMenuFont -foreground black -tearoff 0 
    $site_6_0.men32 add radiobutton \
        -value Radio_A -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#ffff00} -command {#radio_a} \
        -font [vTcl:font:getFontFromDescr "-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Radio-A 
    $site_6_0.men32 add radiobutton \
        -value Radio_B -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#00ff00} -command {#radio_b} \
        -font [vTcl:font:getFontFromDescr "-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label Radio-B 
    $site_6_0.men32 add checkbutton \
        -selectcolor {#990000} -variable Check_1 -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#ff0000} -command {#check1} \
        -compound left \
        -font [vTcl:font:getFontFromDescr "-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} \
        -image [vTcl:image:get_image [file join / home pavao {Python Files} {Trading 2.0} Isaac openfold.gif]] \
        -label {Check 1} 
    $site_6_0.men32 add checkbutton \
        -variable Check_2 -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#ff0000} -command {#check2} \
        -font [vTcl:font:getFontFromDescr "-family sans-serif -size -12 -weight normal -slant roman -underline 0 -overstrike 0"] \
        -foreground {#000000} -label {Check 2} 
    $site_3_0 add cascade \
        -menu "$site_3_0.men34" -activebackground {#d9d9d9} \
        -activeforeground {#000000} -background {#990000} -compound left \
        -font [vTcl:font:getFontFromDescr "-family RaghuMalayalam -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground {#ffff00} -label File -menu "$site_3_0.men32" \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#990000} -compound left \
        -font [vTcl:font:getFontFromDescr "-family RaghuMalayalam -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground {#ffff00} -label Edit -menu "$site_3_0.men43" \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#990000} -compound left \
        -font [vTcl:font:getFontFromDescr "-family RaghuMalayalam -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground {#ffff00} -label Info 
    menu $site_3_0.men43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -font TkMenuFont -foreground black -tearoff 0 
    $site_3_0.men43 add command \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#ff0000} -command {#cpuinfo} \
        -font [vTcl:font:getFontFromDescr "-family {DejaVu Sans Mono} -size 12 -weight bold -slant roman -underline 0 -overstrike 0"] \
        -foreground white -label {CPU Info} 
    ###################
    # SETTING GEOMETRY
    ###################

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top32 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

