#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 06, 2018 04:53:33 PM CET  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import cpu_info

def set_Tk_var():
    global IRS
    IRS = tk.StringVar()
    global Charity
    Charity = tk.StringVar()
    global Check_1
    Check_1 = tk.StringVar()
    global Check_2
    Check_2 = tk.StringVar()
    global combobox
    combobox = tk.StringVar()

def check1():
    print('isaacInterface_support.check1')
    sys.stdout.flush()

def check2():
    print('isaacInterface_support.check2')
    sys.stdout.flush()

def copy():
    print('isaacInterface_support.copy')
    sys.stdout.flush()

def cpuinfo():
    cpu_info.vp_start_gui()

def cut():
    print('isaacInterface_support.cut')
    sys.stdout.flush()

def no():
    print('isaacInterface_support.no')
    sys.stdout.flush()

def paste():
    print('isaacInterface_support.paste')
    sys.stdout.flush()

def post():
    print('isaacInterface_support.post')
    sys.stdout.flush()

def quit():
    print('isaacInterface_support.quit')
    sys.stdout.flush()

def radio_a():
    print('isaacInterface_support.radio_a')
    sys.stdout.flush()

def radio_b():
    print('isaacInterface_support.radio_b')
    sys.stdout.flush()

def save():
    print('isaacInterface_support.save')
    sys.stdout.flush()

def sync():
    print('isaacInterface_support.sync')
    sys.stdout.flush()

def yes():
    print('isaacInterface_support.yes')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import isaacInterface.py
    isaacInterface.py.vp_start_gui()
