#! /usr/bin/env python
#
# Support module generated by PAGE version 4.6
# In conjunction with Tcl version 8.6
#    Feb 11, 2016 06:35:21 PM
#    Nov 06, 2018 02:17:33 PM CET  platform: Linux

import sys
import cpu_info

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = 0
except ImportError:
    import tkinter.ttk as ttk
    py3 = 1

def set_Tk_var():
    # These are Tk variables used passed to Tkinter and must be
    # defined before the widgets using them are created.
    global IRS
    IRS = StringVar()

    global Charity
    Charity = StringVar()

    global Check_1
    Check_1 = StringVar()

    global Check_2
    Check_2 = StringVar()

def cpuinfo():
    cpu_info.vp_start_gui()

def no():
    print('menu_support.no')
    sys.stdout.flush()

def post():
    print('menu_support.post')
    sys.stdout.flush()

def sync():
    print('menu_support.sync')
    sys.stdout.flush()

def yes():
    print('menu_support.yes')
    sys.stdout.flush()

def check1():
    print('isaacInterface_support.check1')
    sys.stdout.flush()

def check2():
    print('isaacInterface_support.check2')
    sys.stdout.flush()

def copy():
    print('isaacInterface_support.copy')
    sys.stdout.flush()

def cut():
    print('isaacInterface_support.cut')
    sys.stdout.flush()

def paste():
    print('isaacInterface_support.paste')
    sys.stdout.flush()

def quit():
    print('isaacInterface_support.quit')
    sys.stdout.flush()
    sys.exit()

def radio_a():
    print('isaacInterface_support.radio_a')
    sys.stdout.flush()

def radio_b():
    print('isaacInterface_support.radio_b')
    sys.stdout.flush()

def save():
    print('isaacInterface_support.save')
    sys.stdout.flush()

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

if __name__ == '__main__':
    import isaacInterface.py
    isaacInterface.py.vp_start_gui()
